Site\FrontEndBundle\Entity\Site:
    type: entity
    table: site
#    repositoryClass: Site\FrontEndBundle\Repository\SiteRepository
        
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        priview:
            type: string
            length: '4000'
        content:
            type: text
        dateAdd:
            type: datetime
        slug:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    
    manyToMany:
        tags:
            targetEntity: Sania
            inversedBy: site
            joinTable:
                name: sait_sania
                joinColumns:
                    post_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }

